# Generated by Django 4.2 on 2023-05-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='task',
            field=models.CharField(default='Database', max_length=30),
        ),
    ]
