# Generated by Django 4.2 on 2023-05-04 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='startDate',
            field=models.DateField(default=datetime.date(2023, 5, 4), verbose_name='Start date'),
        ),
    ]
